GET http://localhost:8080/subscribers

###

GET http://localhost:8080/subscribers/27

###

POST http://localhost:8080/subscribers
Content-Type: application/json

{
    "name": "John Doe",
    "subscribedToChannel": "channel"
}

###

PATCH http://localhost:8080/subscribers/27
Content-Type: application/json

{
    "name": "Jane Doe",
    "subscribedToChannel": "channel"
}

###

DELETE  http://localhost:8080/subscribers/27
